#  1. Test parsing cwa
#  2. Check output epoch files haven't changed

name: cwa

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cwa:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Compile java files
      run: |
        java -version
        javac -cp accelerometer/java/JTransforms-3.1-with-dependencies.jar accelerometer/java/*.java

    - name: Pip install
      run: |
        pip install --upgrade pip
        pip install .

   # - name: Lint with flake8
   #   run: |
   #     # stop the build if there are Python syntax errors or undefined names
   #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
   #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
   #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Download a sample cwa file and process it
      run: |
        wget -P data/ http://gas.ndph.ox.ac.uk/aidend/accModels/sample.cwa.gz --quiet
        accProcess --deleteIntermediateFiles False data/sample.cwa.gz

    - name: Compare epoch output
      uses: tianhaoz95/mirror-action@v1.0.1
      with:
         original: referenceFiles/epoch.csv.gz
         mirror: data/sample-epoch.csv.gz



